version: "3.4"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
   
  grafana:
    image: grafana/grafana:latest
    depends_on: 
      - prometheus
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana

  caddy:
    image: caddy:2
    depends_on: 
      - grafana
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 4430:4430

volumes:
  prometheus_data:
  caddy_config:
  caddy_data:
  grafana_data:
