version: "3.4"

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # ports:
    #   - 9090:9090
    networks:
      inter_br:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 80M

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    environment: 
      - GF_INSTALL_PLUGINS=marcusolsson-hourly-heatmap-panel,grafana-piechart-panel
    networks:
      inter_br:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 80M

  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    volumes:
      - pihole_dnsmasq:/etc/dnsmasq.d
      - ./config/pihole/data:/etc/pihole
    environment:
      TZ: "America/Toronto"
      WEBPASSWORD: "pihole_access"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      inter_br:
      dns_br:
        ipv4_address: 10.5.0.5

  pihole_monitoring:
    image: ekofr/pihole-exporter:latest
    restart: unless-stopped
    environment:
      PIHOLE_HOSTNAME: "pihole"
      PIHOLE_PASSWORD: "pihole_access"
      INTERVAL: "30s"
      PORT: "9617"
    networks:
      inter_br:

  coredns:
    image: coredns/coredns:latest
    depends_on:
      - pihole
    volumes:
      - ./config/coredns/Corefile:/Corefile
    restart: unless-stopped
    ports:
      - 53:53/udp
    networks:
      inter_br:
      dns_br:
        ipv4_address: 10.5.0.6

  dnsdist:
    build: ./config/dnsdist
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - coredns
    command: ["-C", "/etc/dnsdist/dnsdist.conf", "--verbose"]
    volumes:
      - ./config/dnsdist/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
    networks:
      inter_br:
      dns_br:
        ipv4_address: 10.5.0.7

  caddy:
    image: caddy:2
    depends_on:
      - grafana
      - pihole
      - dnsdist
    restart: unless-stopped
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 443:443
    networks:
      inter_br:
      app_br:

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
    networks:
      inter_br:

  openvpn_exporter:
    build: ./config/openvpn-exporter/
    container_name: openvpn_exporter
    restart: unless-stopped
    volumes:
      - /var/log/openvpn/status.log:/etc/openvpn_exporter/server.status
    networks:
      inter_br:
  
  rbn_exporter:
    image: ewpratten/rbn_exporter:latest
    container_name: rbn_exporter
    restart: unless-stopped
    networks:
      inter_br:
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M

  

volumes:
  prometheus_data:
  caddy_config:
  caddy_data:
  grafana_data:
  pihole_dnsmasq:


networks:
  inter_br:
    driver: bridge
  app_br:
    driver: bridge
  dns_br:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
