version: "3.4"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      inter_br:

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    networks:
      inter_br:

  pihole:
    image: pihole/pihole:latest
    volumes:
      - pihole_dnsmasq:/etc/dnsmasq.d
      - ./config/pihole/data:/etc/pihole
    environment:
      TZ: "America/Toronto"
      WEBPASSWORD: "pihole_access"
    networks:
      inter_br:
      dns_br:
        ipv4_address: 10.5.0.5

  pihole_monitoring:
    image: ekofr/pihole-exporter:latest
    environment:
      PIHOLE_HOSTNAME: "pihole"
      PIHOLE_PASSWORD: "pihole_access"
      INTERVAL: "30s"
      PORT: "9617"
    networks:
      inter_br:

  caddy:
    image: caddy:2
    depends_on:
      - grafana
      - pihole
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 4430:4430
    networks:
      inter_br:

  coredns:
    image: coredns/coredns:latest
    depends_on:
      - pihole
    volumes:
      - ./config/coredns/Corefile:/Corefile
    ports:
      - 5300:5300/udp
    networks:
      inter_br:
      dns_br:
        ipv4_address: 10.5.0.6

  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    ports:
      - 8080:1194
    restart: always
    volumes:
      - ./config/openvpn/data:/etc/openvpn
      - ./config/openvpn/tmp:/tmp
    networks:
      inter_br:
  
  openvpn_monitoring:
    image: kumina/openvpn-exporter
    depends_on:
      - openvpn
    volumes:
      - ./config/openvpn/tmp/openvpn-status.log:/etc/openvpn_exporter/server.status:ro
    command: /bin/openvpn_exporter -openvpn.status_paths /etc/openvpn_exporter/server.status

volumes:
  prometheus_data:
  caddy_config:
  caddy_data:
  grafana_data:
  pihole_dnsmasq:

networks:
  inter_br:
    driver: bridge
  dns_br:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
