global:
  scrape_interval: 15s # default is 1 minute
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: caddy
    static_configs:
      - targets: ["caddy:2018"]
  - job_name: coredns
    static_configs:
      - targets: ["coredns:9153"]
  - job_name: pihole
    static_configs:
      - targets: ["pihole_monitoring:9617"]
  - job_name: openvpn
    static_configs:
      - targets: ["openvpn_monitoring:9176"]
