version: '3.4'

services:
  mysql:
    image: mariadb:10.3
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - cloudlog_database:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      cloudlog_internal:
        ipv4_address: 10.5.0.3
    
  
  cloudlog:
    image: waarlandit/cloudlog
    container_name: cloudlog
    depends_on: 
      - mysql
    volumes:
      - ./config:/var/www/html/application/config
      - cloudlog_backup:/var/www/html/application/backup
      - cloudlog_uploads:/var/www/html/application/uploads
    networks:
      vpn-setup_app_br:
      cloudlog_internal:
        ipv4_address: 10.5.0.2

volumes: 
  cloudlog_database:
  cloudlog_backup:
  cloudlog_uploads:

networks: 
  cloudlog_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
  vpn-setup_app_br:
    external: true